/// Flutter icons Surca
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Surca
///      fonts:
///       - asset: fonts/Surca.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Surca {
  Surca._();

  static const _kFontFam = 'Surca';

  static const IconData vaccine = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData animal = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData incident = const IconData(0xe802, fontFamily: _kFontFam);
}
